# file: php7.2/tasks/configure.yml

- name: PHP | correct PHP version selected
  alternatives:
    name: php
    path: /usr/bin/php7.2

- name: PHP | Update the php.ini (cli)
  template:
    src: etc_php72_cli_php.ini.j2
    dest: /etc/php/7.2/cli/php.ini
    owner: root
    group: root
    mode: 0644

- name: PHP | Update the php.ini (apache2)
  template:
    src: etc_php72_apache2_php.ini.j2
    dest: /etc/php/7.2/apache2/php.ini
    owner: root
    group: root
    mode: 0644
  notify:
    - restart apache
