---
- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install System Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - python-software-properties

- name: Add ppa Repository
  become: yes
  apt_repository: repo=ppa:ondrej/{{ php_ppa }}

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install Extra Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - "{{ sys_packages }}"
