# file: php5/tasks/configure.yml

- name: PHP5 | correct PHP version selected
  alternatives:
    name: php
    path: /usr/bin/php5.6

- name: PHP5 | Update the php.ini
  template:
    src: etc_php55_apache2_php.ini.j2
    dest: /etc/php/5.5/apache2/php.ini
    owner: root
    group: root
    mode: 0644
  notify:
    - restart apache
