---
galaxy_info:
  author: "Mario Kehl"
  description: "Ansible role that compiles and installs Ruby 2.4 (https://www.ruby-lang.org) and Bundler (http://bundler.io)."
  license: MIT
  min_ansible_version: 1.4
  platforms:
    - name: Amazon
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  categories:
    - development
dependencies:
  - joshualund.ruby-common
