---
- name: stop mailcatcher
  systemd:
    name: mailcatcher
    state: stopped

- name: start mailcatcher
  systemd:
    name: mailcatcher
    state: started

- name: restart mailcatcher
  systemd:
    name: mailcatcher
    state: restarted

- name: force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: enable service mailcatcher
  systemd:
    name: mailcatcher
    enabled: yes
