# file: phpcommon/tasks/configure.yml

- name: PHP7.2 | Set up APC configuration (apc.ini)
  template:
    src: etc_php72_mods-available_apcu.ini.j2
    dest: /etc/php/7.2/mods-available/apcu.ini
    owner: root
    group: root
    mode: 0644
  notify:
    - restart apache

- name: PHP7 | Set up XDebug configuration (xdebug.ini)
  template:
    src: etc_php72_mods-available_xdebug.ini.j2
    dest: /etc/php/7.2/mods-available/xdebug.ini
    owner: root
    group: root
    mode: 0644
  notify:
    - restart apache
