---
- hosts: all
  become: true
  vars:
    doc_root: /var/www
    sys_packages:
    - sendmail
    - nfs-common
    - nfs-kernel-server
    - portmap
    - git
    - graphicsmagick
    - imagemagick
    - openjdk-7-jdk
    - unzip
    - mailutils
    php_packages:
    - php7.0-mysql
    - php7.0-curl
    - php7.0-imagick
    - php7.0-gd
    - php7.0-redis
    - php7.0-mbstring
    - php7.0-mcrypt
    - php7.0-soap
    - php7.0-xml
    - php7.0-zip
    - php7.0-apcu
    - php7.0-dev #needed for xdebug
    - php-pear #needed for xdebug
    - php7.0-xdebug
    php_ppa: php
  roles:
    - init
    - locale
    - apache
    - mysql
    - php7
    - phpcommon
    - phpcomposer
    - joshualund.ruby-common
    - perltwiesekt.ruby-2.4
    - perlmonkey.mailcatcher
    - mailcatcher-php
