---
- hosts: all
  become: true
  vars:
    doc_root: /var/www
    sys_packages:
    - sendmail
    - nfs-common
    - nfs-kernel-server
    - portmap
    - git
    - graphicsmagick
    - imagemagick
    - openjdk-7-jdk
    - unzip
    - mailutils
    php_packages:
    - php5.5-mysql
    - php5.5-curl
    - php5.5-imagick
    - php5.5-gd
    - php5.5-redis
    - php5.5-mbstring
    - php5.5-soap
    - php5.5-xml
    - php5.5-zip
    - php5.5-apcu
    - php5.5-dev #needed for xdebug
    - php-pear #needed for xdebug
    - php5.5-xdebug
    php_ppa: php
  roles:
    - init
    - locale
    - apache
    - mysql
    - php5
    - phpcommon
    - phpcomposer
    - joshualund.ruby-common
    - perltwiesekt.ruby-2.3
    - perlmonkey.mailcatcher
    - mailcatcher-php
