---
- hosts: all
  become: true
  vars:
    doc_root: /var/www
    sys_packages:
    - sendmail
    - nfs-common
    - nfs-kernel-server
    - portmap
    - git
    - graphicsmagick
    - imagemagick
    - openjdk-11-jdk
    - unzip
    - mailutils
    - mcrypt
    php_packages:
    - php7.2-intl
    - php7.2-mysql
    - php7.2-curl
    - php-imagick
    - php7.2-gd
    - php-redis
    - php7.2-mbstring
    - php7.2-soap
    - php7.2-xml
    - php7.2-zip
    - php-apcu
    - php7.2-dev #needed for xdebug
    - php-pear #needed for xdebug
    - php-xdebug
    php_ppa: php
  roles:
    - init
    - locale
    - apache
    - mysql
    - php7.2
    - phpcommon
    - phpcomposer
    - joshualund.ruby-common
    - perltwiesekt.ruby-2.4
    - perlmonkey.mailcatcher
    - mailcatcher-php
