- name: Install mailcatcher dependencies
  apt: pkg={{ item }} state=present
  with_items:
      - build-essential
      - sqlite3
      - libsqlite3-dev
      - ruby-dev
      - ruby

- name: Check for mailcatcher
  stat:
    path=/usr/local/bin/mailcatcher
  register: mailcatcher_installed

- name: Install Mailcatcher
  command: gem install mailcatcher
  when: not mailcatcher_installed.stat.exists

- name: Make Mailcatcher symlinks
  file: path=/usr/local/bin/{{ item }}
        src={{ ruby_location }}/bin/{{ item }}
        state=link
  with_items:
    - "{{ mailcatcher_symlinks }}"
  when: not mailcatcher_installed.stat.exists

- name: Create systemctl script for mailcatcher
  template: src=mailcatcher.service.j2 dest=/etc/systemd/system/mailcatcher.service mode=0644
  notify:
    - force systemd to reread configs
    - restart mailcatcher
    - enable service mailcatcher
